#!/usr/bin/env python3
"""Reproduce the native figure table from the recovered packed catalogue.

Default is --check (read-only). --write changes only space_catalog.rs. The JSON
is retained as source data; native binaries embed the derived arrays and stars.
"""
from pathlib import Path
import argparse
import json
import math
import struct

ROOT = Path(__file__).resolve().parents[1]
HERE = ROOT / 'crates/render/src'

def build():
    raw = (HERE / 'space-data/stars.bin').read_bytes()
    if len(raw) != 9827 * 8:
        raise ValueError('Recovered catalogue size changed; review provenance first')
    directions = []
    for ra, dec, _, _ in struct.iter_unpack('<Hhhh', raw):
        ra, dec = ra / 65535 * math.tau, dec / 32767 * math.pi / 2
        directions.append((math.cos(dec)*math.cos(ra), math.cos(dec)*math.sin(ra), math.sin(dec)))
    figures = json.loads((HERE / 'space-data/constellation-figures.json').read_text())
    if len(figures) != 88 or sum(len(f['lines']) for f in figures) != 674:
        raise ValueError('Recovered figure set changed; review provenance first')
    lines = ['// Generated from the recovered real-sky-data.js. Do not hand-edit.',
             '// Hipparcos positions; Stellarium Western figures (CC BY-SA, see space-data/NOTICE.md).',
             'pub(super) const LINES: &[[u16; 2]] = &[']
    for figure in figures:
        lines.append('    // ' + figure['name'])
        for a, b in figure['lines']:
            if not (0 <= a < len(directions) and 0 <= b < len(directions)):
                raise ValueError('Figure index outside catalogue')
            lines.append(f'    [{a}, {b}],')
    lines += ['];', 'pub(super) const LABELS: &[(&str, [f32; 3])] = &[']
    for figure in sorted(figures, key=lambda f: f['id'] != 'Ori'):
        if figure['anchor'] is None:
            ids = list(dict.fromkeys(i for pair in figure['lines'] for i in pair))
            v = [sum(directions[i][axis] for i in ids) for axis in range(3)]
            length = math.sqrt(sum(x*x for x in v))
            v = [x / length for x in v]
        else:
            v = directions[figure['anchor']]
        name = json.dumps(figure['name'].upper(), ensure_ascii=False)
        lines.append(f'    ({name}, [{v[0]:.10f}, {v[1]:.10f}, {v[2]:.10f}]),')
    return '\n'.join(lines + ['];', ''])

def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument('--write', action='store_true')
    args = p.parse_args()
    target = HERE / 'space_catalog.rs'
    rendered = build()
    if args.write:
        target.write_text(rendered)
        print('Wrote', target)
    elif target.read_text() != rendered:
        raise SystemExit('Generated catalogue differs; review before running --write')
    else:
        print('PASS: catalogue regenerated byte-for-byte (674 segments, 88 labels)')

if __name__ == '__main__':
    main()
